export enum Genero {
  Hombre = 'Hombre',
  Mujer = 'Mujer',
  UnicornioTricolor = 'UnicornioTricolor',
  MapacheAlbino = 'MapacheAlbino',
  TanqueDeGuerra = 'TanqueDeGuerra',
  HelicopteroApache = 'HelicopteroApache',
  MonoCapuchino = 'MonoCapuchino',
  DobleElefanteTelepataDeGuerra = 'DobleElefanteTelepataDeGuerra',
  TitanCargero = 'TitánCargero', 
  OpelCorsa = 'OpelCorsa',
  BocadilloDeChorizo = 'BocadilloDeChorizo',
  CR7 = 'CR7',
  Messi = 'Messi',
  RecreativoDeHuelva = 'RecreativoDeHuelva',
  CampoConGrillo = 'CampoConGrillo',
  CochinitoBaconQueso = 'CochinitoBaconQueso',
  NoComedorDeJamon = 'NoComedorDeJamon',
  RobaCobre = 'RobaCobre',
  SeaAndKong = 'SeaAndKong',
  Illojuaner = 'Illojuaner',
  TortugaNinja = 'TortugaNinja',
  BenjaminErPescao = 'BenjaminErPescao',
  TermotanqueDeNoquis = 'TermotanqueDeÑoquis',
  ComePalomas = 'ComePalomas'
}